version: '2'
services:
  app:
    container_name: app-starter
    build: .
    image: node-express-mongo-starter
    command: "npm run ${BUILD_ENVIRONMENT}"
    volumes:
      - "./${SRC_VOLUME}:/usr/app/src"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/starter
  mongo:
    container_name: mongo
    image: mongo:4.0.0-xenial
    volumes:
      - ./data:/data/db
      - ./backup:/backup
    ports:
      - "27017:27017"      
