version: '2'
services:
  app:
    build: .
    container_name: app
    image: node-express-mongo-starter
    command: "npm run ${BUILD_ENVIRONMENT}"
    volumes:
      - "./${SRC_VOLUME}:/usr/app/src"
      - "./config:/usr/app/config"
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      - TAG=NODE EXPRESS MONGO STARTER
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/starterDB
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
      - ./backup:/backup
    ports:
      - "27017:27017"      
